# Generated by Django 5.1.1 on 2025-01-10 08:35

import util.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("image", util.utils.CompressedImageField(upload_to="news/")),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
                "db_table": "news",
            },
        ),
    ]
