# Generated by Django 5.1.1 on 2025-01-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="news",
            table=None,
        ),
    ]
