# Generated by Django 5.1.1 on 2025-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="description_tk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_tk",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
