# Generated by Django 5.1.1 on 2025-01-19 15:10

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_description_en_news_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(upload_to="news/"),
        ),
    ]
