# Generated by Django 5.1.1 on 2025-01-20 09:07

import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=util.utils.CompressedImageField(
                blank=True, max_size_mb=20, null=True, upload_to="news/"
            ),
        ),
    ]
