# Generated by Django 5.1.1 on 2025-01-23 10:03

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="news/"
            ),
        ),
    ]
