# Generated by Django 5.1.1 on 2025-02-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habarlasmak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Uznuksiz Bilim Merkezi", max_length=100),
                ),
                ("gmail", models.CharField(max_length=255, verbose_name="Gmail")),
                ("phone", models.CharField(max_length=255, verbose_name="Phone")),
                (
                    "instagram",
                    models.CharField(max_length=255, verbose_name="Instagram"),
                ),
                ("tiktok", models.CharField(max_length=255, verbose_name="TikTok")),
            ],
            options={
                "verbose_name": "Habarlasmak",
                "verbose_name_plural": "Habarlasmak",
            },
        ),
    ]
