# Generated by Django 5.1.1 on 2025-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("percentage", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "discount item",
                "verbose_name_plural": "discount items",
                "db_table": "discount_item",
            },
        ),
    ]
