# Generated by Django 5.1.1 on 2025-01-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="discountitem",
            table=None,
        ),
    ]
