# Generated by Django 5.1.1 on 2025-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0002_alter_discountitem_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountitem",
            name="description_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountitem",
            name="description_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountitem",
            name="description_tk",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
