# Generated by Django 5.1.1 on 2025-01-10 18:41

import util.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", util.utils.CompressedImageField(upload_to="courses/")),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=200)),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "db_table": "courses",
            },
        ),
    ]
