# Generated by Django 5.1.1 on 2025-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_tk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_tk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
