# Generated by Django 5.1.1 on 2025-01-19 15:10

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_description_en_course_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(upload_to="courses/"),
        ),
    ]
