# Generated by Django 5.1.1 on 2025-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_tk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
