# Generated by Django 5.1.1 on 2024-12-27 16:23

import django.db.models.deletion
import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        upload_to="banners/",
                        validators=[util.validator.validate_image],
                    ),
                ),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "db_table": "banner",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=200)),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="DiscountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("percentage", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "discount item",
                "verbose_name_plural": "discount items",
                "db_table": "discount_item",
            },
        ),
        migrations.CreateModel(
            name="SocialActivity",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("experience", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="teachers/")),
                ("likes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "db_table": "teachers",
            },
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video",
                    models.FileField(
                        upload_to="videos/",
                        validators=[util.validator.validate_video_extension],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="videos/", validators=[util.validator.validate_image]
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "db_table": "videos",
            },
        ),
        migrations.CreateModel(
            name="ActivityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="social_activity_images/")),
                (
                    "social_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="school.socialactivity",
                    ),
                ),
            ],
        ),
    ]
