# Generated by Django 5.1.1 on 2025-01-09 09:45

import django.db.models.deletion
import util.utils
import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Big cart",
                "verbose_name_plural": "Big carts",
                "db_table": "bigCart",
            },
        ),
        migrations.CreateModel(
            name="CartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    util.utils.CompressedImageField(
                        blank=True, null=True, upload_to="cartImages/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=200, validators=[util.validator.validate_email]
                    ),
                ),
                ("comment", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "db_table": "contact",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "contents",
                "db_table": "content",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", util.utils.CompressedImageField(upload_to="images/")),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_content",
                        to="school.content",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(related_name="images", to="school.image"),
                ),
            ],
            options={
                "verbose_name": "main",
                "verbose_name_plural": "main",
                "db_table": "main",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("image", util.utils.CompressedImageField(upload_to="news/")),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="SmallCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ManyToManyField(
                        related_name="smallCart", to="school.cartimage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Small cart",
                "verbose_name_plural": "Small carts",
                "db_table": "smallCart",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", util.utils.CompressedImageField(upload_to="teachers/")),
                ("major", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "db_table": "teacher",
            },
        ),
        migrations.RemoveField(
            model_name="activityimage",
            name="social_activity",
        ),
        migrations.DeleteModel(
            name="Teachers",
        ),
        migrations.AlterModelOptions(
            name="socialactivity",
            options={
                "verbose_name": "social activity",
                "verbose_name_plural": "social activities",
            },
        ),
        migrations.RemoveField(
            model_name="banner",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="socialactivity",
            name="description",
        ),
        migrations.RemoveField(
            model_name="socialactivity",
            name="name",
        ),
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="image",
            field=util.utils.CompressedImageField(
                blank=True, null=True, upload_to="banner/"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=util.utils.CompressedImageField(default=1, upload_to="courses/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="socialactivity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=util.utils.CompressedImageField(upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/webm/",
                validators=[util.validator.validate_video_extension],
            ),
        ),
        migrations.AlterModelTable(
            name="socialactivity",
            table="socialActivity",
        ),
        migrations.AddField(
            model_name="socialactivity",
            name="bigCart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.bigcart",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bigcart",
            name="image",
            field=models.ManyToManyField(related_name="bigCart", to="school.cartimage"),
        ),
        migrations.AddField(
            model_name="socialactivity",
            name="smallCart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.smallcart",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ActivityImage",
        ),
    ]
