# Generated by Django 5.1.1 on 2024-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="main_images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="teachers/")),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "db_table": "teacher",
            },
        ),
        migrations.DeleteModel(
            name="Teachers",
        ),
        migrations.AddField(
            model_name="banner",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default=1, upload_to="courses/"),
            preserve_default=False,
        ),
    ]
