# Generated by Django 5.1.1 on 2025-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_bigcart_cartimage_contact_content_image_main_news_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main",
            name="content",
        ),
        migrations.AddField(
            model_name="main",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="main",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
