# Generated by Django 5.1.1 on 2025-01-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_remove_main_content_main_description_main_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialactivity",
            name="bigCart",
        ),
        migrations.RemoveField(
            model_name="socialactivity",
            name="smallCart",
        ),
        migrations.AddField(
            model_name="bigcart",
            name="social_activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.socialactivity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="smallcart",
            name="social_activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.socialactivity",
            ),
            preserve_default=False,
        ),
    ]
