# Generated by Django 5.1.1 on 2024-12-28 06:29

import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountitem",
            name="icon",
            field=models.ImageField(
                blank=True,
                upload_to="discounts/",
                validators=[utils.validator.validate_image],
            ),
        ),
    ]
