# Generated by Django 5.1.1 on 2025-01-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_remove_socialactivity_bigcart_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bigcart",
            name="image",
        ),
        migrations.RemoveField(
            model_name="smallcart",
            name="image",
        ),
        migrations.AddField(
            model_name="bigcart",
            name="image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.cartimage",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="smallcart",
            name="image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.cartimage",
            ),
            preserve_default=False,
        ),
    ]
