# Generated by Django 5.1.1 on 2024-12-28 19:03

import django.db.models.deletion
import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_discountitem_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "text",
                "verbose_name_plural": "texts",
                "db_table": "text",
            },
        ),
        migrations.AlterModelOptions(
            name="main",
            options={"verbose_name": "main", "verbose_name_plural": "main"},
        ),
        migrations.AlterModelTable(
            name="main",
            table="main",
        ),
        migrations.CreateModel(
            name="Advise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "imagecenter",
                    models.ImageField(
                        blank=True,
                        upload_to="advise_images/",
                        validators=[utils.validator.validate_image],
                    ),
                ),
                (
                    "leftside",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leftside",
                        to="school.maintext",
                    ),
                ),
                (
                    "rightside",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rightside",
                        to="school.maintext",
                    ),
                ),
            ],
            options={
                "verbose_name": "advise",
                "verbose_name_plural": "advises",
                "db_table": "advise",
            },
        ),
    ]
