# Generated by Django 5.1.1 on 2024-12-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_maintext_alter_main_options_alter_main_table_advise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="banner",
            new_name="image",
        ),
    ]
