# Generated by Django 5.1.1 on 2025-01-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_remove_bigcart_image_remove_smallcart_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bigcart",
            options={},
        ),
        migrations.AlterModelOptions(
            name="smallcart",
            options={},
        ),
        migrations.AlterField(
            model_name="bigcart",
            name="image",
            field=models.ManyToManyField(
                related_name="big_cart", to="school.cartimage"
            ),
        ),
        migrations.AlterField(
            model_name="bigcart",
            name="social_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="big_carts",
                to="school.socialactivity",
            ),
        ),
        migrations.AlterField(
            model_name="smallcart",
            name="image",
            field=models.ManyToManyField(
                related_name="small_cart", to="school.cartimage"
            ),
        ),
        migrations.AlterField(
            model_name="smallcart",
            name="social_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="small_carts",
                to="school.socialactivity",
            ),
        ),
        migrations.AlterModelTable(
            name="bigcart",
            table=None,
        ),
        migrations.AlterModelTable(
            name="smallcart",
            table=None,
        ),
    ]
