# Generated by Django 5.1.1 on 2024-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_rename_banner_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advise",
            name="imagecenter",
        ),
        migrations.RemoveField(
            model_name="discountitem",
            name="icon",
        ),
        migrations.AddField(
            model_name="advise",
            name="image",
            field=models.ImageField(default=1, upload_to="advise_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discountitem",
            name="image",
            field=models.ImageField(default=1, upload_to="discounts/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=models.ImageField(upload_to="videos/"),
        ),
    ]
