# Generated by Django 5.1.1 on 2024-12-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_remove_advise_imagecenter_remove_discountitem_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
