# Generated by Django 5.1.1 on 2024-12-30 07:17

import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_banner_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="",
                        validators=[util.validator.validate_image],
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
                "db_table": "news",
            },
        ),
    ]
