# Generated by Django 5.1.1 on 2024-12-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0009_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Advise",
        ),
        migrations.DeleteModel(
            name="MainText",
        ),
    ]
