# Generated by Django 5.1.1 on 2025-01-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contact",
            table=None,
        ),
    ]
