# Generated by Django 5.1.1 on 2025-02-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footerdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Habarlasmak",
            new_name="FooterData",
        ),
        migrations.AlterModelOptions(
            name="footerdata",
            options={"verbose_name": "FooterData", "verbose_name_plural": "FooterData"},
        ),
    ]
