# Generated by Django 5.1.1 on 2025-01-23 10:53

import util.compressedFields
import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_tk", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                (
                    "video",
                    models.FileField(
                        upload_to="videos/",
                        validators=[util.validator.validate_video_extension],
                    ),
                ),
                (
                    "image",
                    util.compressedFields.AdvanceThumbnailField(
                        upload_to="videos/image/"
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
            },
        ),
    ]
