# Generated by Django 5.1.1 on 2025-01-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="videos",
            table=None,
        ),
    ]
