# Generated by Django 5.1.1 on 2025-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_alter_videos_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="videos",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="videos",
            name="title_tk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
