# Generated by Django 5.1.1 on 2025-01-13 15:33

import apps.video.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_videos_title_en_videos_title_ru_videos_title_tk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="image",
        ),
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=apps.video.models.CompressedVideoField(
                default=1, max_length=255, upload_to="videos/"
            ),
            preserve_default=False,
        ),
    ]
