# Generated by Django 5.1.1 on 2025-01-13 15:36

import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_remove_videos_image_alter_videos_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="image",
            field=util.utils.CompressedImageField(
                default=1, max_length=255, max_size_mb=20, upload_to="videos/"
            ),
            preserve_default=False,
        ),
    ]
