# Generated by Django 5.1.1 on 2025-01-13 18:09

import util.compressedFields
import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_videos_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=util.utils.CompressedImageField(
                max_size_mb=20, upload_to="videos/images"
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=util.compressedFields.CompressedVideoField(upload_to=""),
        ),
    ]
