# Generated by Django 5.1.1 on 2025-01-13 18:18

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0006_alter_videos_image_alter_videos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=util.compressedFields.CompressedVideoField(upload_to="videos/"),
        ),
    ]
