# Generated by Django 5.1.1 on 2025-01-19 15:10

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0007_alter_videos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                upload_to="videos/image/"
            ),
        ),
    ]
