# Generated by Django 5.1.1 on 2025-01-10 05:44

import django.db.models.deletion
import util.utils
import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    util.utils.CompressedImageField(
                        blank=True, null=True, upload_to="banner/"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "db_table": "banner",
            },
        ),
        migrations.CreateModel(
            name="CartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    util.utils.CompressedImageField(
                        blank=True, null=True, upload_to="cartImages/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=200, validators=[util.validator.validate_email]
                    ),
                ),
                ("comment", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "db_table": "contact",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "content",
                "verbose_name_plural": "contents",
                "db_table": "content",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", util.utils.CompressedImageField(upload_to="courses/")),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=200)),
                ("price", models.FloatField()),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="DiscountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("percentage", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "discount item",
                "verbose_name_plural": "discount items",
                "db_table": "discount_item",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", util.utils.CompressedImageField(upload_to="images/")),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("image", util.utils.CompressedImageField(upload_to="news/")),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
                "db_table": "news",
            },
        ),
        migrations.CreateModel(
            name="SocialActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "social activity",
                "verbose_name_plural": "social activities",
                "db_table": "socialActivity",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", util.utils.CompressedImageField(upload_to="teachers/")),
                ("major", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "db_table": "teacher",
            },
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/webm/",
                        validators=[util.validator.validate_video_extension],
                    ),
                ),
                ("image", util.utils.CompressedImageField(upload_to="videos/")),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "db_table": "videos",
            },
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "images",
                    models.ManyToManyField(related_name="images", to="school.image"),
                ),
            ],
            options={
                "verbose_name": "main",
                "verbose_name_plural": "main",
                "db_table": "main",
            },
        ),
        migrations.CreateModel(
            name="SmallCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ManyToManyField(
                        related_name="small_cart", to="school.cartimage"
                    ),
                ),
                (
                    "social_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_carts",
                        to="school.socialactivity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BigCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ManyToManyField(
                        related_name="big_cart", to="school.cartimage"
                    ),
                ),
                (
                    "social_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_carts",
                        to="school.socialactivity",
                    ),
                ),
            ],
        ),
    ]
