# Generated by Django 5.1.1 on 2025-01-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_delete_banner_remove_bigcart_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main",
            name="images",
        ),
    ]
