# Generated by Django 5.1.1 on 2025-01-10 12:33

import util.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_remove_main_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="videos/webm/",
                validators=[util.validator.validate_video_extension],
            ),
        ),
    ]
