# Generated by Django 5.1.1 on 2025-01-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_videos_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
