# Generated by Django 5.1.1 on 2025-01-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_remove_smallcart_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
