# Generated by Django 5.1.1 on 2025-01-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_delete_content_delete_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="DiscountItem",
        ),
    ]
