# Generated by Django 5.1.1 on 2025-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="description_tk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="major_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="major_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="major_tk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name_tk",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="surname_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="surname_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="surname_tk",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
