# Generated by Django 5.1.1 on 2025-01-13 09:07

import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_description_en_teacher_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=util.utils.CompressedImageField(
                max_size_mb=15, upload_to="teachers/"
            ),
        ),
    ]
