# Generated by Django 5.1.1 on 2025-01-20 05:18

import util.compressedFields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_alter_teacher_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                default=1, upload_to="teachers/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major_en",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major_ru",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="major_tk",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name_tk",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="surname",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="surname_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="surname_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="surname_tk",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
