# Generated by Django 5.1.1 on 2025-01-20 07:55

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0006_alter_teacher_image_alter_teacher_major_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="teacher/images"
            ),
        ),
    ]
