# Generated by Django 5.1.1 on 2025-01-20 08:37

import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0007_alter_teacher_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=util.utils.CompressedImageField(
                blank=True, max_size_mb=20, null=True, upload_to="teacher"
            ),
        ),
    ]
