# Generated by Django 5.1.1 on 2025-01-23 10:42

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0008_alter_teacher_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="teacher"
            ),
        ),
    ]
