# Generated by Django 5.1.1 on 2025-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0009_alter_teacher_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=15,
            ),
        ),
    ]
