# Generated by Django 5.1.1 on 2025-01-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="banner",
            table="banner_01",
        ),
    ]
