# Generated by Django 5.1.1 on 2025-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0002_alter_banner_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="description_tk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_tk",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
