# Generated by Django 5.1.1 on 2025-01-19 15:10

import util.compressedFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0003_banner_description_en_banner_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=util.compressedFields.AdvanceThumbnailField(
                blank=True, null=True, upload_to="banner/"
            ),
        ),
    ]
