# Generated by Django 5.1.1 on 2025-01-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0005_alter_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="title",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title_tk",
        ),
    ]
