# Generated by Django 5.1.1 on 2025-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0006_remove_banner_title_remove_banner_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
