# Generated by Django 5.1.1 on 2025-01-10 17:53

import django.db.models.deletion
import util.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    util.utils.CompressedImageField(
                        blank=True, null=True, upload_to="cartImages/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "social activity",
                "verbose_name_plural": "social activities",
                "db_table": "socialActivity",
            },
        ),
        migrations.CreateModel(
            name="SmallCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ManyToManyField(
                        related_name="small_cart", to="socialactivity.cartimage"
                    ),
                ),
                (
                    "social_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_carts",
                        to="socialactivity.socialactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "small cart",
                "verbose_name_plural": "small carts",
                "db_table": "smallCart",
            },
        ),
    ]
