# Generated by Django 5.1.1 on 2025-01-20 17:54

import util.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialactivity", "0002_alter_image_social_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=util.utils.CompressedImageField(
                blank=True, max_size_mb=20, null=True, upload_to="images/"
            ),
        ),
    ]
